version: '3'
services:
  db:
    image: mysql:5.7.32
    container_name: db
    # build:
    #   context: .
    #   dockerfile: ./web/db/Dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: laravel_web
      MYSQL_ROOT_PASSWORD: replace_mysql_root_password
      MYSQL_USER: dev
      MYSQL_PASSWORD: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./web/mysql/my.cnf:/etc/mysql/my.cnf
  php:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./web/:/var/www/html/
      - ./web/php.ini:/usr/local/etc/php/conf.d/php.ini
    # ports:
    #   - 8000:9000
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
      # - 8004:82
    # working_dir: /var/www/laravel
    volumes:
      - ./web/:/var/www/html/
      - ./web/nginx/conf.d/:/etc/nginx/conf.d/
      # - ./client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # web:
  #   container_name: web
  #   build: ./client
  #   ports:
  #     - 8004:82
  #   restart: always
  #   networks:
  #     - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
