version: '3'
services:
  php:
    build:
      args:
        user: rani
        uid: 1000
      context: ./
      dockerfile: ./web/Dockerfile
    container_name: php-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./web/:/var/www
    networks:
      - app-network

  db:
    image: postgres:9.5-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - app-network

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./web/:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  web:
    container_name: web
    build:
      context: ./client
      args:
        REACT_APP_BACKEND_ADDRESS: ${REACT_APP_BACKEND_ADDRESS}
    ports:
      - 8004:82
    restart: always
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge