version: '3'
services:
  dbmysql:
    build:
      context: .
      dockerfile: ./web/dbmysql/Dockerfile
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: xxxx
      MYSQL_USER: xxxx
      MYSQL_PASSWORD: xxxxx
  php:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    working_dir: /var/www/laravel
    container_name: php
    volumes:
      - php1:/var/www/laravel
    depends_on:
      - dbmysql
    entrypoint:
      - php-fpm

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www/laravel
    volumes:
      - ./web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - php1:/var/www/laravel
    links:
      - php
    ports:
      - 8080:80

volumes:
  php1:
