version: "3.9"
services:
  web:
    container_name: web
    build: .
    ports:
      - 8004:82

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
