version: '3'
services:
  php:
    build:
      args:
        user: rani
        uid: 1000
      context: ./
      dockerfile: ./web/Dockerfile
    container_name: php-app
    restart: unless-stopped
    # tty: true
    # environment:
    #   SERVICE_NAME: php
    #   SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./web/:/var/www
      # - ./web/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network

  db:
    image: postgres:9.5-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - app-network

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    # tty: true
    ports:
      - 8000:80
      # - 443:443
      # - 8004:82
    # working_dir: /var/www/laravel
    volumes:
      - ./web/:/var/www
      - ./nginx:/etc/nginx/conf.d
      # - ./client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  web:
    container_name: web
    build: ./client
    ports:
      - 8004:82
    restart: always
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
# volumes:
#   dbdata:
#     driver: local
